'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Business_Solutions.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1480383006_xfce_system_exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1480383006_xfce-system-exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _71_1thermo_lab_6753_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("71_1thermo_lab_6753_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_application_exit_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions-application-exit-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Add_record() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add record", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Add_record1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add record1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Add_record2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add record2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Analysis_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Analysis-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_remove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_remove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_remove11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_remove11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_addressHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_addressHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Book_angleHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Book_angleHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Book_openHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Book_openHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Book_openHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Book_openHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_reportHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_reportHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Book_StackOfReportsHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Book_StackOfReportsHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Book_StackOfReportsHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Book_StackOfReportsHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CalculatorHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalculatorHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calendar_icon_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar-icon-18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calendar_icon_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar-icon-24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cashbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cashbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Check_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Check-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_edit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_edit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_edit2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_edit2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Contact_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contact-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Content_Reorder_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Content-Reorder-24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Content_Reorder_241() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Content-Reorder-241", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Content_Reorder_242() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Content-Reorder-242", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Content_Reorder_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Content-Reorder-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Content_Reorder_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Content-Reorder-321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Content_Reorder_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Content-Reorder-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CutHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CutHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CutHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CutHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CutHS2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CutHS2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property data_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property data_add1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_add1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property data_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Database_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Database_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Database-641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_accept1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_accept1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_remove1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_remove1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Delete1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DocumentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DocumentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Documents_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Documents-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Download_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_pencil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_pencil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_pencil_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_pencil_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_pencil_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_pencil_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Electronic_Billing_Machine_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Electronic-Billing-Machine-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property erase_db() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("erase_db", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property erase_db1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("erase_db1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property erase_db2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("erase_db2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property erase_db3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("erase_db3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Filter2HS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Filter2HS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FindHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FindHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_add1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_add1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_add11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_add11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gnome_Application_Exit_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gnome-Application-Exit-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Head_physician_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Head-physician-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property health_wall_paper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("health_wall_paper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HomeHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HomeHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property if_edit_173002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit_173002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property if_edit_1730021() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit_1730021", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property if_edit_find_replace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit-find-replace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property if_edit_find_replace1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit-find-replace1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property if_edit_find_replace2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit-find-replace2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property if_edit_find_replace3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit-find-replace3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property if_edit_find_replace4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit-find-replace4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property if_icon_edit_314724() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_icon-edit_314724", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Keys_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Keys-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lab_Wallpaper_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lab Wallpaper 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Locked_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locked-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Medical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Medical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Medical_invoice_information_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Medical-invoice-information-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property microscope_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("microscope_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property microscope_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("microscope_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Money_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Money-24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Money_241() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Money-241", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Money_64x64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Money-64x64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Money_Bag_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Money_Bag_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Money_Calculator_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Money_Calculator_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Money_Calculator_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Money_Calculator_641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MonthlyViewHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MonthlyViewHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewDocumentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewDocumentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewDocumentHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewDocumentHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewDocumentHS2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewDocumentHS2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OrganizerHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OrganizerHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OrganizerHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OrganizerHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_process() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_process", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_process1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_process1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_process11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_process11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientData() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientData", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientFile1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientFile1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientFile2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientFile2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientFile21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientFile21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientFile22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientFile22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientFile23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientFile23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientFile24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientFile24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientFile25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientFile25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PatientFile3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PatientFile3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property People_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("People-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property People_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("People-641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Printer_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Printer-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrintHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrintHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrintHS2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintHS2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrintPreviewHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintPreviewHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrintPreviewHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintPreviewHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ProtectFormHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProtectFormHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rebuild_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rebuild-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remove_field() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove_field", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Report_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Report-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SaveFormDesignHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveFormDesignHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scanner_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanner_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scanner_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanner_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StopHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StopHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StopHS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StopHS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property treatment_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treatment_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property treatment_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treatment_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property treatment_2561() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treatment_2561", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property urology_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("urology_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property urology_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("urology_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Users_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Users-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WarningHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WarningHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Wooden_Box_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wooden-Box-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
